name: super trend bot

on:
  push:
    branches:
      - main  # Change to the appropriate branch name

jobs:
  build:
    runs-on: ubuntu-latest



    - name: Install dependencies
      run: pip install -r requirements.txt # Change to the appropriate command for your app
      
  
    - name: Run Streamlit app
